### PR TITLE
Update xml-rs to 0.2

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by vberger** [comment]
Thanks!

**Comment by SimonSapin** [comment]
Could you publish this on crates.io? Thanks!

**Comment by vberger** [comment]
Yes, syncing the versionning with the other crates and doing it.

**Comment by vberger** [comment]
Done. :smile:

**Comment by SimonSapin** [comment]
Thanks! This makes our "no duplicate crates" lint happy and unblocks https://github.com/servo/servo/pull/9096 :)

**Pull request merged**
